# Default initial positions for taihu_revo1_description's ros2_control fake system

initial_positions:
  L_ELBOW_Y: 0
  L_SHOULDER_P: 0
  L_SHOULDER_R: 0
  L_SHOULDER_Y: 0
  L_WRIST_P: 0
  L_WRIST_R: 0
  L_WRIST_Y: 0
  R_ELBOW_Y: 0
  R_SHOULDER_P: 0
  R_SHOULDER_R: 0
  R_SHOULDER_Y: 0
  R_WRIST_P: 0
  R_WRIST_R: 0
  R_WRIST_Y: 0
  waist_lift_joint: 0
  waist_rotate_joint: 0
  left_index_proximal_joint: 0
  left_middle_proximal_joint: 0
  left_pinky_proximal_joint: 0
  left_ring_proximal_joint: 0
  left_thumb_metacarpal_joint: 0
  left_thumb_proximal_joint: 0
  right_index_proximal_joint: 0
  right_middle_proximal_joint: 0
  right_pinky_proximal_joint: 0
  right_ring_proximal_joint: 0
  right_thumb_metacarpal_joint: 0
  right_thumb_proximal_joint: 0
