# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  L_ELBOW_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_SHOULDER_P:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_SHOULDER_R:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_SHOULDER_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_WRIST_P:
    has_velocity_limits: true
    max_velocity: 4.1900000000000004
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_WRIST_R:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 2.5
  L_WRIST_Y:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_ELBOW_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_SHOULDER_P:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_SHOULDER_R:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_SHOULDER_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_WRIST_P:
    has_velocity_limits: true
    max_velocity: 4.1900000000000004
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_WRIST_R:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 2.5
  R_WRIST_Y:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 2.5
  waist_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  waist_rotate_joint:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_index_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_index_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_middle_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_middle_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_pinky_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_pinky_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_ring_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_ring_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_thumb_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.5303
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_thumb_metacarpal_joint:
    has_velocity_limits: true
    max_velocity: 2.6175000000000002
    has_acceleration_limits: true
    max_acceleration: 2.5
  left_thumb_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.5303
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_index_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_index_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_middle_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_middle_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_pinky_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_pinky_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_ring_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_ring_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.2685
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_thumb_distal_joint:
    has_velocity_limits: true
    max_velocity: 2.5303
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_thumb_metacarpal_joint:
    has_velocity_limits: true
    max_velocity: 2.6175000000000002
    has_acceleration_limits: true
    max_acceleration: 2.5
  right_thumb_proximal_joint:
    has_velocity_limits: true
    max_velocity: 2.5303
    has_acceleration_limits: true
    max_acceleration: 2.5
