# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - waist_group_controller
    - left_hand_index_controller
    - left_hand_middle_controller
    - left_hand_pinky_controller
    - left_hand_ring_controller
    - left_hand_thumb_controller
    - right_hand_index_controller
    - right_hand_middle_controller
    - right_hand_pinky_controller
    - right_hand_ring_controller
    - right_hand_thumb_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    action_ns: follow_joint_trajectory
    default: true

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    action_ns: follow_joint_trajectory
    default: true

  waist_group_controller:
    type: FollowJointTrajectory
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    action_ns: follow_joint_trajectory
    default: true

  left_hand_index_controller:
    type: FollowJointTrajectory
    joints:
      - left_index_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  left_hand_middle_controller:
    type: FollowJointTrajectory
    joints:
      - left_middle_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  left_hand_pinky_controller:
    type: FollowJointTrajectory
    joints:
      - left_pinky_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  left_hand_ring_controller:
    type: FollowJointTrajectory
    joints:
      - left_ring_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  left_hand_thumb_controller:
    type: FollowJointTrajectory
    joints:
      - left_thumb_metacarpal_joint
      - left_thumb_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  right_hand_index_controller:
    type: FollowJointTrajectory
    joints:
      - right_index_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  right_hand_middle_controller:
    type: FollowJointTrajectory
    joints:
      - right_middle_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  right_hand_pinky_controller:
    type: FollowJointTrajectory
    joints:
      - right_pinky_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  right_hand_ring_controller:
    type: FollowJointTrajectory
    joints:
      - right_ring_proximal_joint
    action_ns: follow_joint_trajectory
    default: true

  right_hand_thumb_controller:
    type: FollowJointTrajectory
    joints:
      - right_thumb_metacarpal_joint
      - right_thumb_proximal_joint
    action_ns: follow_joint_trajectory
    default: true
