# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    waist_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_index_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_middle_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_pinky_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_ring_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_thumb_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_index_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_middle_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_pinky_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_ring_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_thumb_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    left_arm_position_controller:
      type: position_controllers/JointGroupPositionController

    right_arm_position_controller:
      type: position_controllers/JointGroupPositionController

left_arm_controller:
  ros__parameters:
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_controller:
  ros__parameters:
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

waist_group_controller:
  ros__parameters:
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

left_hand_index_controller:
  ros__parameters:
    joints:
      - left_index_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
left_hand_middle_controller:
  ros__parameters:
    joints:
      - left_middle_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
left_hand_pinky_controller:
  ros__parameters:
    joints:
      - left_pinky_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
left_hand_ring_controller:
  ros__parameters:
    joints:
      - left_ring_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
left_hand_thumb_controller:
  ros__parameters:
    joints:
      - left_thumb_metacarpal_joint
      - left_thumb_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
   
right_hand_index_controller:
  ros__parameters:
    joints:
      - right_index_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
right_hand_middle_controller:
  ros__parameters:
    joints:
      - right_middle_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    
right_hand_pinky_controller:
  ros__parameters:
    joints:
      - right_pinky_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

right_hand_ring_controller:
  ros__parameters:
    joints:
      - right_ring_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

right_hand_thumb_controller:
  ros__parameters:
    joints:
      - right_thumb_metacarpal_joint
      - right_thumb_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

left_arm_position_controller:
  ros__parameters:
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_position_controller:
  ros__parameters:
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position
