# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  L_ELBOW_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  L_SHOULDER_P:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  L_SHOULDER_R:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  L_SHOULDER_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  L_WRIST_P:
    has_velocity_limits: true
    max_velocity: 4.1900000000000004
    has_acceleration_limits: false
    max_acceleration: 0
  L_WRIST_R:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: false
    max_acceleration: 0
  L_WRIST_Y:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: false
    max_acceleration: 0
  R_ELBOW_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  R_SHOULDER_P:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  R_SHOULDER_R:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  R_SHOULDER_Y:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  R_WRIST_P:
    has_velocity_limits: true
    max_velocity: 4.1900000000000004
    has_acceleration_limits: false
    max_acceleration: 0
  R_WRIST_R:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: false
    max_acceleration: 0
  R_WRIST_Y:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: false
    max_acceleration: 0
  head_left_right_joint:
    has_velocity_limits: true
    max_velocity: 1.1339999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  head_up_down_joint:
    has_velocity_limits: true
    max_velocity: 1.1339999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  waist_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: false
    max_acceleration: 0
  waist_rotate_joint:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: false
    max_acceleration: 0
