# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - waist_group_controller
    - head_up_down_group_controller
    - head_left_right_group_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    action_ns: follow_joint_trajectory
    default: true

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    action_ns: follow_joint_trajectory
    default: true
    
  waist_group_controller:
    type: FollowJointTrajectory
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    action_ns: follow_joint_trajectory
    default: true
    
  head_up_down_group_controller:
    type: FollowJointTrajectory
    joints:
      - head_up_down_joint
    action_ns: follow_joint_trajectory
    default: true
    
  head_left_right_group_controller:
    type: FollowJointTrajectory
    joints:
      - head_left_right_joint
    action_ns: follow_joint_trajectory
    default: true
    