# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    waist_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_up_down_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_left_right_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    left_arm_position_controller:
      type: position_controllers/JointGroupPositionController

    right_arm_position_controller:
      type: position_controllers/JointGroupPositionController

    waist_group_position_controller:
      type: position_controllers/JointGroupPositionController

left_arm_controller:
  ros__parameters:
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_controller:
  ros__parameters:
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position
      
waist_group_controller:
  ros__parameters:
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      
head_up_down_group_controller:
  ros__parameters:
    joints:
      - head_up_down_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      
head_left_right_group_controller:
  ros__parameters:
    joints:
      - head_left_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      

left_arm_position_controller:
  ros__parameters:
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_Y
      - L_WRIST_P
      - L_WRIST_Y
      - L_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

right_arm_position_controller:
  ros__parameters:
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_Y
      - R_WRIST_P
      - R_WRIST_Y
      - R_WRIST_R
    command_interfaces:
      - position
    state_interfaces:
      - position

waist_group_position_controller:
  ros__parameters:
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
