# Default initial positions for VB2_robot_description's ros2_control fake system

initial_positions:
  head_left_right_joint: 0
  head_up_down_joint: 0
  l_j1: 0
  l_j2: 0
  l_j3: 0
  l_j4: 0
  l_j5: 0
  l_j6: 0
  l_j7: 0
  r_j1: 0
  r_j2: 0
  r_j3: 0
  r_j4: 0
  r_j5: 0
  r_j6: 0
  r_j7: 0
  waist_lift_joint: 0
  waist_rotate_joint: 0
  left_hand_indexMCP: 0
  left_hand_littleMCP: 0
  left_hand_middleMCP: 0
  left_hand_ringMCP: 0
  left_hand_thumbCMC: 0
  left_hand_thumbMCP: 0
  right_hand_indexMCP: 0
  right_hand_littleMCP: 0
  right_hand_middleMCP: 0
  right_hand_ringMCP: 0
  right_hand_thumbCMC: 0
  right_hand_thumbMCP: 0
