trajectory_execution:
# 此参数缩放运动计划的执行持续时间。缩放因子为1.2表示计划可以比原始计划的时间长20%。
  allowed_execution_duration_scaling: 1.2
# 目标持续时间设置了一个边距。在这种情况下，允许额外0.5秒来实现目标。
  allowed_goal_duration_margin: 0.5
# 允许的机器人起始状态的容差。0.01的容差表示起始状态应在指定的起始状态的0.01单位范围内。
  allowed_start_tolerance: 0.01
# 当设置为true时，MoveIt会监视计划轨迹的持续时间
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - waist_group_controller
    - head_group_controller
    - left_index_controller
    - left_middle_controller
    - left_thumb_controller
    - left_ring_controller
    - left_little_controller
    - right_thumb_controller
    - right_index_controller
    - right_middle_controller
    - right_ring_controller
    - right_little_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - l_j1
      - l_j2
      - l_j3
      - l_j4
      - l_j5
      - l_j6
      - l_j7
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - r_j1
      - r_j2
      - r_j3
      - r_j4
      - r_j5
      - r_j6
      - r_j7
    action_ns: follow_joint_trajectory
    default: true
  waist_group_controller:
    type: FollowJointTrajectory
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    action_ns: follow_joint_trajectory
    default: true
  head_group_controller:
    type: FollowJointTrajectory
    joints:
      - head_up_down_joint
      - head_left_right_joint
    action_ns: follow_joint_trajectory
    default: true


  left_index_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_indexMCP
    action_ns: follow_joint_trajectory
    default: true
  left_middle_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_middleMCP
    action_ns: follow_joint_trajectory
    default: true
  left_thumb_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_thumbCMC
      - left_hand_thumbMCP
    action_ns: follow_joint_trajectory
    default: true
  left_ring_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_ringMCP
    action_ns: follow_joint_trajectory
    default: true
  left_little_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_littleMCP
    action_ns: follow_joint_trajectory
    default: true
  right_thumb_controller:
    type: FollowJointTrajectory
    joints:
      - right_hand_thumbCMC
      - right_hand_thumbMCP
    action_ns: follow_joint_trajectory
    default: true
  right_index_controller:
    type: FollowJointTrajectory
    joints:
      - right_hand_indexMCP
    action_ns: follow_joint_trajectory
    default: true
  right_middle_controller:
    type: FollowJointTrajectory
    joints:
      - right_hand_middleMCP
    action_ns: follow_joint_trajectory  
    default: true
  right_ring_controller:
    type: FollowJointTrajectory
    joints:
      - right_hand_ringMCP
    action_ns: follow_joint_trajectory
    default: true
  right_little_controller:
    type: FollowJointTrajectory
    joints:
      - right_hand_littleMCP
    action_ns: follow_joint_trajectory
    default: true
